### ISSUE TITLE
ImportError: sys.meta_path is None

### ISSUE THREAD

**Issue by tylfin** [yzyio/adidas-multi-session#1]
Testing the `transfer_session` function synchronously resulted in 

> Traceback (most recent call last):
  File "run.py", line 29, in <module>
    run(url)
  File "adidas-multi-session/bot.py", line 112, in run
    transfer_session(driver, proxy, proxy_auth, user_agent)
  File "adidas-multi-session/bot.py", line 38, in transfer_session
    chrome.get(url)
  File "adidas-multi-session/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "adidas-multi-session/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "adidas-multi-session/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"23521.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.3 x86_64)

> Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x102e0ec88>>
Traceback (most recent call last):
  File "adidas-multi-session/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
  File "adidas-multi-session/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 149, in stop
  File "adidas-multi-session/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 120, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by bommels** [comment]
Did you run this with proxies and USE_PROXIES to True?

**Comment by tylfin** [comment]
Ah, this turned out to be me failing to close the window properly.
