### ISSUE TITLE
Error on updated ver.

### ISSUE THREAD

**Issue by CashHash123** [yzyio/adidas-multi-session#23]
Threw me the following error for each, i only copy one here.

Working proxies: 6 - starting script..
2017-02-23 07:44:49,598 - INFO: Checking if session d66d4e20-f9c5-11e6-bf3b-4189                                                                                                                                  0ecfb93c is past splash
2017-02-23 07:44:49,598 - INFO: Checking if session ca9a4440-f9c5-11e6-ade8-b16e                                                                                                                                  3515c6b6 is past splash
2017-02-23 07:44:49,602 - INFO: Checking if session da720d80-f9c5-11e6-9aa0-fdb5                                                                                                                                  a8865e4b is past splash
2017-02-23 07:44:49,683 - INFO: [New Thread] Transferring session d25f3ff0-f9c5-                                                                                                                                  11e6-8d20-63f3c09729bc
2017-02-23 07:44:49,684 - INFO: [New Thread] Transferring session ce7e3530-f9c5-                                                                                                                                  11e6-a478-9bd9cbb183c1
2017-02-23 07:44:49,688 - INFO: [New Thread] Transferring session ca9a4440-f9c5-                                                                                                                                  11e6-ade8-b16e3515c6b6
2017-02-23 07:44:49,691 - INFO: [New Thread] Transferring session da720d80-f9c5-                                                                                                                                  11e6-9aa0-fdb5a8865e4b
2017-02-23 07:44:49,692 - INFO: [New Thread] Transferring session c77e8550-f9c5-                                                                                                                                  11e6-9fdb-eb0e5fa9c326
2017-02-23 07:44:49,698 - INFO: [New Thread] Transferring session d66d4e20-f9c5-                                                                                                                                  11e6-bf3b-41890ecfb93c
2017-02-23 07:44:54,149 - INFO: [CHROME/PROXY] Login with username:password
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\BD\AppData\Local\Programs\Python\Python36-32\lib\threading.py",                                                                                                                                   line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\BD\AppData\Local\Programs\Python\Python36-32\lib\threading.py",                                                                                                                                   line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\BD\adidas-multi-session-master\bot.py", line 41, in transfer_se                                                                                                                                  ssion
    chrome.add_cookie(cookie)
  File "C:\Users\BD\AppData\Local\Programs\Python\Python36-32\lib\site-packages\                                                                                                                                  selenium\webdriver\remote\webdriver.py", line 671, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "C:\Users\BD\AppData\Local\Programs\Python\Python36-32\lib\site-packages\                                                                                                                                  selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\BD\AppData\Local\Programs\Python\Python36-32\lib\site-packages\                                                                                                                                  selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: <unknown>: Failed to set                                                                                                                                   the 'cookie' property on 'Document': Cookies are disabled inside 'data:' URLs.
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cf                                                                                                                                  d9),platform=Windows NT 10.0.14393 x86_64)

**Comment by bommels** [comment]
That's probably an invalid proxy, you need to have working proxies to open Chrome

**Comment by CashHash123** [comment]
oh ok, i didnt add any, this was loaded, i assumed to test

Looks good to go with fresh proxies?

**Comment by CashHash123** [comment]
Received new error.  Can ignore?


Tried a live proxy, got this.




2017-02-23 08:24:57,000 - INFO: [2/2] Proxy using IP: ERROR
The requested URL could not be retrieved
The following error was encountered while trying to retrieve the URL: http://tools.yzy.io/ip.php
Access Denied.
Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.
Your cache administrator is webmaster.

Generated Thu, 23 Feb 2017 13:24:54 GMT by Guilhermezkz (squid/3.3.8)
2017-02-23 08:25:02,606 - INFO: [2/2] Proxy Test Success

Adidas Multi Session by YZY.io (BETA) (V0.22)
Proxies loaded: 2

**Comment by bommels** [comment]
Try another chromedriver version to resolve this (2.7/2.8/2.9)
