### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by hnguyen81** [yzyio/adidas-multi-session#24]
getting the following error message:

2017-02-23 08:13:39,797 - INFO: [1/1] Testing proxy: ('104.144.169.20:3128', None)
2017-02-23 08:13:42,295 - INFO: [1/1] Proxy using IP: 104.144.169.20
2017-02-23 08:13:48,332 - INFO: [1/1] Proxy Test Success

Working proxies: 1 - starting script..
2017-02-23 08:13:48,333 - INFO: Checking if session e5ac35f0-f9c9-11e6-acaa-a743a6c6141b is past splash
2017-02-23 08:13:48,353 - INFO: [New Thread] Transferring session e5ac35f0-f9c9-11e6-acaa-a743a6c6141b
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Hai/Documents/adidas-multi-session-master/bot.py", line 32, in transfer_session
    chrome.get(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"35157.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.3 x86_64)

**Comment by ctmchugh** [comment]
Try using chromedriver 2.27. That fixed the issue for me. https://chromedriver.storage.googleapis.com/index.html?path=2.27/

**Comment by hnguyen81** [comment]
thanks.  that worked.

**Comment by ThatZacman** [comment]
I've tried 2.27 and terminal gave me the error:
 
selenium.common.exceptions.WebDriverException: Message: <unknown>: Failed to set the 'cookie' property on 'Document': Cookies are disabled inside 'data:' URLs.

**Comment by ayyantalib** [comment]
Also got the same error as ThatZacman. Also, chromedriver.exe always stops working.

**Comment by monarck** [comment]
Getting the same "Failed to set the 'cookie' property on 'Document': Cookies are disabled inside 'data:' URLs." error. 

**Additional info:**
`(Session info: chrome=56.0.2924.87)
(Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.10.5 x86_64)`

I'm testing using private proxies for now before purchasing dedicated proxies. Could that be the issue?

**Comment by bommels** [comment]
Try other chromedriver versions
