### ISSUE TITLE
after transfering session

### ISSUE THREAD

**Issue by v812v** [yzyio/adidas-multi-session#33]
2017-02-25 02:31:55,800 - INFO: [1/1] Proxy Test Success

Working proxies: 1 - starting script..
2017-02-25 02:31:55,802 - INFO: Checking if session 6das55dc0-fae9-11e6-91ab-6b03
41c84fee is past splash
2017-02-25 02:32:05,938 - INFO: [New Thread] Transferring session 6d9as553c0-fae9-
11e6-917b-6b054141c84fee
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python stuff\que.io\bot.py", line 32, in transfer_session
    chrome.get(url)
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", li
ne 248, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", li
ne 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\errorhandler.py",
 line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.e
xecutionContextCreated has invalid 'context': {"auxData":{"frameId":"2456.1","is
Default":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.1 SP1 x86_64)

already tried using another chromedriver 
still same error and after opening chrome window it closes

**Comment by bommels** [comment]
Is the chromedriver file in the same folder as run.py?

**Comment by v812v** [comment]
Yes

**Comment by bommels** [comment]
Try other chromedriver versions

**Comment by v812v** [comment]
tried all version from 2.27 to latest
