### ISSUE TITLE
Error Once Extracting HMAC

### ISSUE THREAD

**Issue by YeezySzn** [yzyio/adidas-multi-session#6]
MacBook-Pro:~ cookmachine$ cd desktop
MacBook-Pro:desktop cookmachine$ cd adidassplash
MacBook-Pro:adidassplash cookmachine$ python3.5 run.py

Adidas Multi Session by YZY.io (BETA) 
Thank you for testing the script, you are on version 0.1

Proxies loaded: 0
Product URL: http://www.adidas.com/yeezy
=> URL is valid

2017-02-13 08:39:38,142 - INFO: Product page loaded on session: 000d9130-f20b-11e6-93f9-ff2da28d159b
2017-02-13 08:39:38,143 - INFO: Checking for hmac in all session cookies.. [10s interval]
2017-02-13 08:39:38,149 - INFO: [HMAC] Cookie found on session 000d9130-f20b-11e6-93f9-ff2da28d159b
2017-02-13 08:39:38,149 - INFO: [New Thread] Transferring session 000d9130-f20b-11e6-93f9-ff2da28d159b
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'bin/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cookmachine/Desktop/AdidasSplash/bot.py", line 34, in transfer_session
    chrome = webdriver.Chrome(executable_path=CHROMEDRIVER_LOCATION, chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x10165a470>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
    self.stop()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 145, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
^CTraceback (most recent call last):
  File "run.py", line 29, in <module>
    run(url)
  File "/Users/cookmachine/Desktop/AdidasSplash/bot.py", line 117, in run
    time.sleep(10)
KeyboardInterrupt
MacBook-Pro:adidassplash cookmachine$

**Comment by bommels** [comment]
Hi, there is no chromedriver executable in the bin folder.
